# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - xcode: "14.3"
            ios: "16.0"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_$.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -scheme BudgetOnTheGo -project BudgetOnTheGo.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14,OS=$' | xcpretty && exit ${PIPESTATUS[0]}
