on:
  push:
    branches:    
      - main
name: Build
jobs:
  iOS:
    name: Unit Tests
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.0,name=iPhone 14']
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          xcodebuild build test ./WeatherWise.xcproject -scheme WeatherWise -destination "${destination}"
    env:
      destination: ${{ matrix.destination }}
