on:
  push:
    branches:    
      - main
name: Build
jobs:
  iOS:
    name: Unit Tests
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.0,name=iPhone 14']
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          mv Optimize/Secrets.swift.example Optimize/Secrets.swift
          xcodebuild build test -workspace ./Optimize.xcworkspace -scheme Optimize -destination "${destination}"
    env:
      destination: ${{ matrix.destination }}
